theme: blowfish
languageCode: en
baseURL: "https://rolbk.com/"
defaultContentLanguage: en
taxonomies:
  tag: "tags"
  category: "categories"
  author: "authors"
  series: "series"
outputs:
  home:
  - html
  section:
  - html
  - rss
  taxonomy:
  - html
  term:
  - html
