main:
  - name: Posts
    pageRef: posts
    weight: 10
  - name: Projects
    pageRef: projects
    weight: 20
  - name: Resume
    pageRef: resume
    weight: 30
  - pre: rss
    url: 'posts/index.xml'
    weight: 40
footer:
  - name: Acknowledgements
    pageRef: acknowledgements
    weight: 10
  - name: Privacy
    pageRef: privacy
    weight: 20
  - name: Polyring
    pageRef: polyring
    weight: 30
