colorScheme: ocean
defaultAppearance: dark
autoSwitchAppearance: false

author:
  name: Emanuel Mairoll
  image: img/author.jpg
  headline: Software Dev // Reverse Engineer // Human
  bio: Forward & Reverse Engineer
  links:
    - github: 'https://github.com/rolbk/'
    - linkedin: 'https://www.linkedin.com/in/rolbk/'
    - envelope: 'mailto:sigmoid_flavors_0u@icloud.com'

header:
  layout: fixed

footer:
  showThemeAttribution: false
  showAppearanceSwitcher: true
  showMenu: true
  showCopyright: true
  showScrollToTop: false

homepage:
  layout: background
  homepageImage: img/background.webp
  showRecent: true
  showRecentItems: 6
  cardView: true
  showMoreLink: true

list:
  # showHero: true
  # heroStyle: background
  showSummary: true
  # cardView: true

article:
  showHero: true
  heroStyle: background
  showAuthor: true
  showAuthorBottom: true
  showTaxonomies: true
